/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('peach-x/components/button')['PButton']
    PConfigProvider: typeof import('peach-x/components/config-provider')['PConfigProvider']
    PDivider: typeof import('peach-x/components/divider')['PDivider']
    PTicker: typeof import('peach-x/components/ticker')['PTicker']
  }
}
